### ISSUE TITLE
Conversion issue.

### ISSUE THREAD

**Issue by dkonigsfeld** [AnakinSklavenwalker/Republic-at-War-Launcher#1]
Is anyone else having a problem with loading in the 1.2 version? I have the 1.1.5 version up and running through steam properties but I can't seem to properly launch the 1.2 version. If anyone knows how to get it to run through steam let me know.

**Comment by AnakinSklavenwalker** [comment]
for 1.1.5 please refer to online tutorials available on youtube. 
after 1.2 is released you can launch the mod with this launcher.

**Comment by SHARPGAM3R** [comment]
When do you expect 1.2 to come out, it must be close, mustn't it?
